### ISSUE TITLE
Ansible: Limit Task to just one host

### ISSUE THREAD

**Issue by deoren** [deoren/notes#10]
## Example

```yaml
---

- name: do a demo
  hosts: groupA

  tasks:
    - name: demo task 1
      debug:
        msg: "this is task 1"

    - name: demo task 2
      fail:
        msg: "this is task 2"
      when: inventory_hostname == "host2"

- name: "Do another demo"
  hosts: groupB

  tasks:
    - name: demo task 3
      debug:
        msg: "this is task 3"

    - name: demo task 4
      debug:
        msg: "this is task 4"
```

## References

- https://www.lynda.com/Ansible-tutorials/Learning-Ansible/555799-2.html
