### ISSUE TITLE
LXD | Ansible | Study syntax for specifying 'config' options

### ISSUE THREAD

**Issue by deoren** [deoren/notes#17]
Here is a valid (or at least "passing") use of the `lxd_containers` module:

## Example 1: Quoted config keys/values

TODO: Not sure how to properly describe the syntax below.

```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: Create a started container
      lxd_container:
        name: mycontainer
        state: started
        config:
          "environment.http_proxy": "{{ lxd_containers_proxy_server | default('') }}"
          "environment.https_proxy": "{{ lxd_containers_proxy_server | default('') }}"
          "environment.ftp_proxy": "{{ lxd_containers_proxy_server | default('') }}"
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: lxd
          alias: ubuntu/xenial/amd64
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
```

## Example 2: Unquoted config key

```yaml
# playbook.yml
---
- hosts: localhost
  # run this task in the host
  connection: local
  tasks:
    - name: create containers
      # get all host names from inventory
      loop: "{{ groups['all'] }}"
      # use lxd_container module from ansible to create containers
      lxd_container:
        # container name is the hostname
        name: "{{ item }}"
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          alias: ubuntu/bionic/amd64
        config:
          # nomad clients need some privileges to be able to run docker containers
          security.nesting: "{{ 'true' if item in ['nomad-client1', 'nomad-client2', 'nomad-client3'] else 'false' }}"
          security.privileged: "{{ 'true' if item in ['nomad-client1', 'nomad-client2', 'nomad-client3'] else 'false' }}"
        devices:
          # configure network interface
          eth0:
            type: nic
            nictype: bridged
            parent: lxdbr0
            # get ip address from inventory
            ipv4.address: "{{ hostvars[item].ip_address }}"
        # # uncomment if you installed lxd using snap
        # url: unix:/var/snap/lxd/common/lxd/unix.socket
```

Now the unquoted syntax here compared to the earlier example.

## Example 3: Unquoted key, apparently valid JSON value

```yaml
- name: "LXD | Create and start container 'test'"
  lxd_container:
    name: test_ansible
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: simplestreams
      alias: ubuntu/bionic/amd64
    profiles: test
    config: { "user.network-config": '{"ethernets": {"eth0": {"addresses": ["10.0.0.115/24"], "gateway4": "10.0.0.1"}}, "version": 2}' }
    state: started
    wait_for_ipv4_addresses: true
```

Similar syntax here, but apparently (to my ignorant eyes) valid JSON syntax vs the YAML syntax seen earlier.

## References

Official module doc:

- https://docs.ansible.com/ansible/latest/modules/lxd_container_module.html

Examples of syntax for the `config` parameter found here:

- https://github.com/ansible/ansible/issues/47009#issue-369827430
- https://dev.to/livioribeiro/using-lxd-and-ansible-to-simulate-infrastructure-2g8l
