### ISSUE TITLE
Ansible | Using register in a loop

### ISSUE THREAD

**Issue by deoren** [deoren/notes#44]
## Example

Here you can see that `results` is a list of dictionaries and how to access them.

```yaml
- hosts: localhost
  gather_facts: no
  vars:
    images:
      - foo
      - bar
  tasks:
    - shell: "echo result-{{item}}"
      register: "r"
      with_items: "{{ images }}"

    - debug: var=r

    - debug: msg="item.item={{item.item}}, item.stdout={{item.stdout}}, item.changed={{item.changed}}"
      with_items: "{{r.results}}"

    - debug: msg="Gets printed only if this item changed - {{item}}"
      when: item.changed == true
      with_items: "{{r.results}}"
```

## References

- https://docs.ansible.com/ansible/latest/user_guide/playbooks_async.html
- https://stackoverflow.com/questions/29512443/register-variables-in-with-items-loop-in-ansible-playbook/29564339

**Comment by deoren** [comment]
Another relevant block:

```yaml
- name: DEBUG | monitoring nodes mail queue flush registered var
  debug:
    var: item
  loop_control:
    label: "{{ item['item']['item'] | default(item['item']) }}"
  with_items:
    - "{{ postqueue_monitoring_nodes_flush['results'] }}"
  # https://stackoverflow.com/a/32218765
  # https://docs.ansible.com/ansible|/latest/user_guide/playbooks_loops.html#using-register-with-a-loop
  when: item is not skipped
```

From the linked stackoverflow.com Answer:

> When you register the result of a loop (e.g. with_items) the registered value will contain a key results which holds a list of all results of the loop.
> 
> The condition not item | skipped takes care of that elements which have been filtered in the original loop (sda) will not be processed.

A later remark notes that the syntax has since changed and should be `item is not skipped` or more specifically `when: item is not skipped`.

The point remains the same however:

**The `results` list contains ALL results, including elements that were filtered out in the original loop**

This is *still* tripping me up.
