### ISSUE TITLE
Docker | Build PHP images for Ubuntu 16.04

### ISSUE THREAD

**Issue by deoren** [deoren/notes#45]
https://github.com/DataDog/docker-library/pull/40/files

Some very useful ideas worth reviewing here.

The Dockerfile contents:

```Dockerfile
FROM ubuntu:16.04

# make Apt non-interactive
RUN echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90circleci \
  && echo 'DPkg::Options "--force-confnew";' >> /etc/apt/apt.conf.d/90circleci

ENV DEBIAN_FRONTEND=noninteractive
# Set timezone to UTC by default
RUN ln -sf /usr/share/zoneinfo/Etc/UTC /etc/localtime

# Use unicode
RUN locale-gen C.UTF-8 || true
ENV LANG=C.UTF-8

RUN set -xe; \
  apt-get update; \ 
  apt-get install software-properties-common python-software-properties; \
  add-apt-repository -y ppa:ondrej/php; \
  apt-get -y clean; rm -rf /var/lib/apt/lists/*  

ARG PHP_VERSION=7.2  
RUN set -xe; \  
  apt-get update; \
  apt-get -y install php${PHP_VERSION} php${PHP_VERSION}-cli php${PHP_VERSION}-common; \
  apt-get -y clean; rm -rf /var/lib/apt/lists/*  
```

The docker-compose.yml contents:

```yaml
version: '3.6'

x-aliases:
  bld: &build
    context: ./
    dockerfile: Dockerfile 

services:    
  ubuntu16.04-7_2:
    build: { <<: *build, args: { PHP_VERSION: 7.2 } }
    image: datadog/docker-library:ddtrace_ubuntu_16_04_php_7_2
  ubuntu16.04-7_1:
    build: { <<: *build, args: { PHP_VERSION: 7.1 } }
    image: datadog/docker-library:ddtrace_ubuntu_16_04_php_7_1
  ubuntu16.04-7_0:
    build: { <<: *build, args: { PHP_VERSION: 7.0 } }
    image: datadog/docker-library:ddtrace_ubuntu_16_04_php_7_0
  ubuntu16.04-5_6:
    build: { <<: *build, args: { PHP_VERSION: 5.6 } }
    image: datadog/docker-library:ddtrace_ubuntu_16_04_php_5_6        
  # ubuntu16.04-5_5:
  #   build: { <<: *build, args: { PHP_VERSION: 5.5 } }
  #   image: datadog/docker-library:ddtrace_ubuntu_16_04_php_5_5
  # ubuntu16.04-5_4:
  #   build: { <<: *build, args: { PHP_VERSION: 5.4 } }
  #   image: datadog/docker-library:ddtrace_ubuntu_16_04_php_5_4    
```
