### ISSUE TITLE
Ansible | 'with_' is evaluated BEFORE 'when' to enable conditional execution per loop item

### ISSUE THREAD

**Issue by deoren** [deoren/notes#51]
From this post: https://github.com/ansible/ansible/issues/17725#issuecomment-249217224:

> As the documentation states, with_ gets evaluated BEFORE when to enable conditional execution per loop item, as such it's evaluation cannot be conditioned to the when.
> http://docs.ansible.com/ansible/playbooks_conditionals.html#loops-and-conditionals

I glanced at the linked documentation and it's not near as clear as @bcoca's explanation in his closing comments. If time permits, I'll try to submit a PR that include's the additional information. Otherwise, the behavior described in the closing comment is not apparent.

I got bit by this with recent work to an Ansible playbook. I attempted to reference an array element that only exists when hosts are processed earlier. If they're skipped, that array (`results` in this case) doesn't exist. I attempted to guard against that with this setup:

```yaml
- name: DEBUG | remaining nodes mail queue flush registered var
  debug:
    var: item
  loop_control:
    label: "{{ item['item']['item'] | default(item['item']) }}"
  with_items:
      - "{{ postqueue_flush_remaining_nodes['results'] }}"
  when: item is not skipped
```
