### ISSUE TITLE
YAML - When to use '-' character?

### ISSUE THREAD

**Issue by deoren** [deoren/notes#82]
- https://www.reddit.com/r/ansible/comments/5jhff3/when_to_use_dash_in_yaml/
- https://yaml.org/spec/1.2/spec.html#Preview

```yaml
-
  name: Mark McGwire
  hr:   65
  avg:  0.278
-
  name: Sammy Sosa
  hr:   63
  avg:  0.288
```

I kept mentally mixing up the `-` character with a Markdown list item, but that's not the case at all. Instead, this is what (I think) we're actually getting:

```json
[
  {"name": "Mark McGwire", "hr": 65, "avg": 0.278},
  {"name": "Sammy Sosa", "hr": 63, "avg": 0.288}
]
```
