### ISSUE TITLE
Ansible: Install Ansible via pip into a virtualenv

### ISSUE THREAD

**Issue by deoren** [deoren/notes#9]
Another example provided by a Lynda.com video series:

```yaml
---
- name: Challenge Me
  hosts: host1

  tasks:
    - name: ansible pip
      pip:
        name: ansible
        virtualenv: ~/challenge1
        
```

This looks like something I want to explore further, so noting here for later review.

## References

- https://www.lynda.com/Ansible-tutorials/Learning-Ansible/555799-2.html
